### ISSUE TITLE
Cloning fails on Windows 10

### ISSUE THREAD

**Issue by fliegera** [in28minutes/spring-microservices-v2#2]
Receive the following when cloning with git bash on Windows 10

`$ git clone https://github.com/in28minutes/spring-microservices-v2.git
Cloning into 'spring-microservices-v2'...
remote: Enumerating objects: 716, done.
remote: Counting objects: 100% (716/716), done.
remote: Compressing objects: 100% (451/451), done.
remote: Total 716 (delta 263), reused 618 (delta 170), pack-reused 0
Receiving objects: 100% (716/716), 3.55 MiB | 1.02 MiB/s, done.
Resolving deltas: 100% (263/263), done.
error: unable to create file 03.microservices/api-gateway/src/main/java/com/in28minutes/microservices/apigateway/ApiGatewayApplication.java: Filename too long
error: unable to create file 03.microservices/api-gateway/src/main/java/com/in28minutes/microservices/apigateway/ApiGatewayConfiguration.java: Filename too long
error: unable to create file 03.microservices/api-gateway/src/test/java/com/in28minutes/microservices/apigateway/ApiGatewayApplicationTests.java: Filename too long
fatal: cannot create directory at '03.microservices/currency-conversion-service/src/main/java/com/in28minutes/microservices/currencyconversionservice': Filename too long
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
`

**Comment by in28minutes** [comment]
Can you download a zip?

**Comment by fliegera** [comment]
Downloading ZIP and extraction works fine

**Comment by in28minutes** [comment]
Awesome. Quick question: What is the path from which you are running the
clone?

**Comment by fliegera** [comment]
This is my Path and it really contains a dash and spaces. The Windows path has a total length of 126 characters

C:\Users\XXX\OneDrive - My  Company name\work\Education\udemy\mastermicroserviceswithspringbootandspringcloud
~/OneDrive - My  Company name/work/Education/udemy/mastermicroserviceswithspringbootandspringcloud

**Comment by ThiagoAnd** [comment]
For file path names too long you could do two things:

Start Git Bash as Administrator

Run command git config --system core.longpaths true
Another way (only for this clone):

git clone -c core.longpaths=true <repo-url>

answer copied from https://stackoverflow.com/questions/52699177/how-to-fix-filename-too-long-error-during-git-clone/52699496
