### ISSUE TITLE
spring-boot:build-image -DskipTests failed to creating image

### ISSUE THREAD

**Issue by ganeshgiri-dev** [in28minutes/spring-microservices-v2#5]
[INFO]     [creator]     ERROR: failed to build: exit status 1
[INFO] [1m------------------------------------------------------------------------[m
[INFO] [1;31mBUILD FAILURE[m
[INFO] [1m------------------------------------------------------------------------[m
[INFO] Total time:  06:05 min
[INFO] Finished at: 2021-04-05T20:16:07+05:30
[INFO] [1m------------------------------------------------------------------------[m
[ERROR] Failed to execute goal [32morg.springframework.boot:spring-boot-maven-plugin:2.4.4:build-image[m [1m(default-cli)[m on project [36mapi-gatway[m: [1;31mExecution default-cli of goal org.springframework.boot:spring-boot-maven-plugin:2.4.4:build-image failed: Builder lifecycle 'creator' failed with status code 145[m -> [1m[Help 1][m
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the [1m-e[m switch.
[ERROR] Re-run Maven using the [1m-X[m switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [1m[Help 1][m http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

**Comment by ravi2519** [comment]
If you are trying on mac m1, then this is bug with m1 and docker compatibility. Seems like underlying JNA doesn't support the M1 architecture. More on this:
https://github.com/spring-projects/spring-boot/issues/24638
